inherits = "meliora"

"comment" = { fg = "comment", modifiers = ["italic"] }

"ui.bufferline" = { fg = "darker-grey" }
"ui.bufferline.active" = { fg = "muted-orange" }

"ui.cursor" = { bg = "pop-black", fg = "pop-white", modifiers = ["italic", "bold"] }
"ui.cursor.insert" = { fg = "selection", bg = "pop-black", modifiers = ["bold"] }
"ui.cursor.match" = { fg = "pop-white", bg = "pop-red", modifiers = ["bold", "underlined"] }

"ui.cursor.primary.normal" = { fg = "pop-black", bg = "pop-white", modifiers = ["bold"] }
"ui.cursor.primary.select" = { fg = "pop-white", bg = "pop-red", modifiers = ["bold", "italic"] }

"ui.cursorline.primary" = { bg = "dark-cyan-blue" }
"ui.cursorline.secondary" = { bg = "selection", modifiers = ["italic", "dim"] }

"ui.highlight" = { fg = "pop-white", bg = "pop-red", modifiers = ["italic"] }
"ui.window" = { fg = "muted-green" }

"ui.selection" = { fg = "pop-black", bg = "pop-white", modifiers = ["bold"] }
"ui.selection.primary" = { fg = "pop-white", bg = "selection", modifiers = ["bold"] }

"ui.gutter" = { bg = "black" }
"ui.gutter.selected" = { fg = "muted-green", bg = "dark-cyan-blue" }
"ui.linenr" = { fg = "muted-orange", bg = "black", modifiers = ["dim"] }
"ui.linenr.selected" = { fg = "muted-green", bg = "dark-cyan-blue", modifiers = ["bold"] }

"ui.virtual" = { fg = "muted-orange", modifiers = ["italic"] }
"ui.virtual.indent-guide" = { fg = "muted-orange" }
"ui.virtual.jump-label" = { fg = "pop-orange", modifiers = ["bold"] }

"ui.text.focus" = { fg = "pop-white", bg = "selection", modifiers = ["bold"] }
"ui.popup" = { fg = "selection", modifiers = ["italic"] }
"ui.menu.selected" = { bg = "selection" , fg = "pop-white", modifiers = ["bold"] }
"ui.background.separator" = { fg = "selection" }
"ui.statusline.inactive" = { fg = "dark_white2", bg = "light_black", modifiers = ["dim"] }

[palette]
darker-grey = "#33302d"
muted-blue = "#5c677d"
muted-green = "#3a4035"
muted-orange = "#504940"
selection = "#0000ff"

pop-red = "#7f0000"
pop-white = "#ffffff"
pop-black = "#000000"
pop-orange = "#d79921"
pop-cyan = "#00FFFF"
dark-cyan-blue = "#1d2021"
faint-green = "#2a5045"
